### ISSUE TITLE
'Adam' object has no attribute 'get_weights'

### ISSUE THREAD

**Issue by Muhammad-Usman678** [Brandes-Lab/proteinbert_data_files#1]
Hi,

I got this error again and again while using example fo fine tuning with signal peptide.

![image](https://github.com/nadavbra/proteinbert_data_files/assets/120212670/12d47ecf-e39c-4cb0-8701-46169c20dcd9)

**Comment by nadavbra** [comment]
Hi @Muhammad-Usman678 
This is not the right repo for questions about ProteinBERT.
You should look at https://github.com/nadavbra/protein_bert
